### PR TITLE
Upgrade to Decidim 0.26

### PR DESCRIPTION
**Pull request by LauraJaimeC**
This PR will update this module to be compatible with Decidim 0.26.

⚠️ Depends on https://github.com/coopdevs/decidim-module-action_delegator/pull/117

### CODE REVIEW

**Comment by tramuntanal** [comment]
@microstudi Friendly reminder

**Comment by microstudi** [comment]
@LauraJaimeC @tramuntanal I've just merge #117, can you rebase this? thanks

**Comment by LauraJaimeC** [comment]
> @LauraJaimeC @tramuntanal I've just merge #117, can you rebase this? thanks

Done!!

**Comment by microstudi** [comment]
@LauraJaimeC looks that some tests are failing!

**Comment by LauraJaimeC** [comment]
> @LauraJaimeC looks that some tests are failing!

Fixed!!!

**Comment by microstudi** [comment]
Thanks @LauraJaimeC !

**Comment by microstudi** [comment]
I've also published the gems as I see I still have access to ti.

**Pull request merged**
