### PR TITLE
Upgrade to decidim@0.24.3

### PR DESCRIPTION
**Pull request by aitorlb**

### CODE REVIEW

**Review by microstudi — CHANGES_REQUESTED** [review]
Please change the test to use 0.24 too
https://github.com/coopdevs/decidim-module-action_delegator/blob/master/.github/workflows/build.yml

**Comment by LauraJaimeC** [comment]
Hi guys! do you know when you'll continue working with this PR to merge?

Thank you!!

**Comment by verarojman** [comment]
@microstudi if it looks good to you we can proceed to merge :)

**Comment by microstudi** [comment]
@verarojman lets go!

**Comment by microstudi** [comment]
@LauraJaimeC we finally managed to merge this. Thanks for the patience!

**Pull request merged**
